import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Lock, TrendingUp, Users, Zap, Target, Mail, MessageSquare } from "lucide-react";
import { Link } from "react-router-dom";
import comingSoon from "@/assets/coming_soon.png";

const playbooks = [
  {
    id: 1,
    title: "How Sarah automated her entire client onboarding",
    category: "Operations",
    author: "Sarah Chen",
    summary: "From lead to signed contract in 24 hours—completely automated. Learn the 5-tool stack that handles proposals, contracts, and kick-off meetings.",
    metrics: "3x faster onboarding, 90% less manual work",
    icon: Users,
    locked: true
  },
  {
    id: 2,
    title: "The 3-tool stack that tripled content output",
    category: "Marketing",
    author: "Marcus Rivera",
    summary: "From 2 blog posts a week to 6—without hiring a single writer. Discover the AI content pipeline that maintains quality at scale.",
    metrics: "300% increase in content, same team size",
    icon: TrendingUp,
    locked: true
  },
  {
    id: 3,
    title: "Automating Sales: A founder's lead-gen agent",
    category: "Sales",
    author: "Jessica Park",
    summary: "Built an AI agent that finds, qualifies, and reaches out to 100+ prospects daily. The complete blueprint from setup to first sale.",
    metrics: "250+ qualified leads/month, 15% conversion rate",
    icon: Target,
    locked: true
  },
  {
    id: 4,
    title: "Zero-code customer support automation",
    category: "Support",
    author: "Alex Thompson",
    summary: "Handle 80% of customer inquiries automatically with a simple chatbot setup. No developers needed, works with your existing tools.",
    metrics: "80% automated responses, 2-hour setup",
    icon: MessageSquare,
    locked: true
  },
  {
    id: 5,
    title: "Email sequences that write themselves",
    category: "Marketing",
    author: "David Kumar",
    summary: "Personalized email campaigns generated by AI, optimized in real-time. See the exact prompts and workflows that 3x'ed open rates.",
    metrics: "3x open rates, 5x reply rates",
    icon: Mail,
    locked: true
  },
  {
    id: 6,
    title: "AI-powered competitive intelligence",
    category: "Strategy",
    author: "Emily Watson",
    summary: "Track competitors, analyze trends, and get weekly insights—all automated. The monitoring system that keeps you ahead of the market.",
    metrics: "Daily competitor updates, 10 hours saved/week",
    icon: Zap,
    locked: true
  }
];

const Playbooks = () => {
  return (
    <div className="min-h-screen pt-24 pb-20">
      {/* Header */}
      <section className="px-4 mb-16">
        <div className="container mx-auto text-center space-y-6 max-w-3xl">
          <h1 className="text-5xl font-bold">
            Real Playbooks.{" "}
            <span className="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
              Real Results.
            </span>
          </h1>
          <p className="text-xl text-muted-foreground">
            Step-by-step workflows from founders who've automated their way to growth. 
            Full playbooks are available to community members only.
          </p>
        </div>
      </section>

      {/* Coming Soon Section */}
      <section className="px-4">
        <div className="container mx-auto max-w-4xl">
          <Card className="bg-card/50 backdrop-blur border-2 border-primary/20">
            <CardContent className="p-12 md:p-16">
              <div className="flex flex-col items-center text-center space-y-8">
                <img
                  src={comingSoon}
                  alt="Coming Soon"
                  className="w-48 h-48 md:w-64 md:h-64 object-cover rounded-2xl shadow-lg"
                />
                <div className="space-y-4">
                  <div className="inline-block px-8 py-3 bg-primary/10 rounded-full">
                    <span className="text-primary font-bold text-2xl">Coming Soon</span>
                  </div>
                  <h2 className="text-3xl md:text-4xl font-bold">
                    Playbooks are brewing...
                  </h2>
                  <p className="text-lg md:text-xl text-muted-foreground max-w-2xl mx-auto leading-relaxed">
                    We're curating incredible workflows and step-by-step guides from founders
                    who've automated their way to growth. Check back soon for real playbooks
                    with real results!
                  </p>
                </div>
              </div>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>
  );
};

export default Playbooks;
