import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Lock, TrendingUp, Users, Zap, Target, Mail, MessageSquare } from "lucide-react";
import { Link } from "react-router-dom";

const playbooks = [
  {
    id: 1,
    title: "How Sarah automated her entire client onboarding",
    category: "Operations",
    author: "Sarah Chen",
    summary: "From lead to signed contract in 24 hours—completely automated. Learn the 5-tool stack that handles proposals, contracts, and kick-off meetings.",
    metrics: "3x faster onboarding, 90% less manual work",
    icon: Users,
    locked: true
  },
  {
    id: 2,
    title: "The 3-tool stack that tripled content output",
    category: "Marketing",
    author: "Marcus Rivera",
    summary: "From 2 blog posts a week to 6—without hiring a single writer. Discover the AI content pipeline that maintains quality at scale.",
    metrics: "300% increase in content, same team size",
    icon: TrendingUp,
    locked: true
  },
  {
    id: 3,
    title: "Automating Sales: A founder's lead-gen agent",
    category: "Sales",
    author: "Jessica Park",
    summary: "Built an AI agent that finds, qualifies, and reaches out to 100+ prospects daily. The complete blueprint from setup to first sale.",
    metrics: "250+ qualified leads/month, 15% conversion rate",
    icon: Target,
    locked: true
  },
  {
    id: 4,
    title: "Zero-code customer support automation",
    category: "Support",
    author: "Alex Thompson",
    summary: "Handle 80% of customer inquiries automatically with a simple chatbot setup. No developers needed, works with your existing tools.",
    metrics: "80% automated responses, 2-hour setup",
    icon: MessageSquare,
    locked: true
  },
  {
    id: 5,
    title: "Email sequences that write themselves",
    category: "Marketing",
    author: "David Kumar",
    summary: "Personalized email campaigns generated by AI, optimized in real-time. See the exact prompts and workflows that 3x'ed open rates.",
    metrics: "3x open rates, 5x reply rates",
    icon: Mail,
    locked: true
  },
  {
    id: 6,
    title: "AI-powered competitive intelligence",
    category: "Strategy",
    author: "Emily Watson",
    summary: "Track competitors, analyze trends, and get weekly insights—all automated. The monitoring system that keeps you ahead of the market.",
    metrics: "Daily competitor updates, 10 hours saved/week",
    icon: Zap,
    locked: true
  }
];

const Playbooks = () => {
  return (
    <div className="min-h-screen pt-24 pb-20">
      {/* Header */}
      <section className="px-4 mb-16">
        <div className="container mx-auto max-w-3xl">
          <h1 className="text-4xl md:text-5xl font-bold mb-6">
            Real Playbooks. <span className="text-primary">Real Results.</span>
          </h1>
          <p className="text-lg text-muted-foreground">
            Step-by-step workflows from founders who've automated their way to growth. 
            Full playbooks are available to community members only.
          </p>
        </div>
      </section>

      {/* Playbooks Grid */}
      <section className="px-4">
        <div className="container mx-auto">
          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-8">
            {playbooks.map((playbook) => (
              <Card key={playbook.id} className="relative overflow-hidden group hover:border-primary/50 transition-colors border border-border">
                <div className="absolute top-4 right-4">
                  <Badge variant={playbook.locked ? "secondary" : "default"} className="text-xs">
                    {playbook.locked ? <><Lock className="w-3 h-3 mr-1" /> Members Only</> : "Free"}
                  </Badge>
                </div>
                
                <CardHeader>
                  <div className={`w-10 h-10 rounded flex items-center justify-center mb-3 ${
                    playbook.category === "Marketing" ? "bg-accent/10" : "bg-primary/10"
                  }`}>
                    <playbook.icon className={`w-5 h-5 ${
                      playbook.category === "Marketing" ? "text-accent" : "text-primary"
                    }`} />
                  </div>
                  <Badge variant="outline" className="w-fit mb-2 text-xs">
                    {playbook.category}
                  </Badge>
                  <CardTitle className="text-lg leading-tight">{playbook.title}</CardTitle>
                  <CardDescription className="text-sm text-muted-foreground">
                    by {playbook.author}
                  </CardDescription>
                </CardHeader>
                
                <CardContent className="space-y-4">
                  <p className="text-sm text-muted-foreground">
                    {playbook.summary}
                  </p>
                  <div className="pt-3 border-t border-border">
                    <p className="text-xs font-semibold text-primary">
                      {playbook.metrics}
                    </p>
                  </div>
                  {playbook.locked && (
                    <div className="pt-2">
                      <Link to="/apply">
                        <Button variant="outline" className="w-full text-sm h-9">
                          Unlock Full Playbook
                        </Button>
                      </Link>
                    </div>
                  )}
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="px-4 mt-20">
        <div className="container mx-auto">
          <Card className="bg-muted/30 border border-border">
            <CardContent className="p-8 md:p-12 text-center space-y-4">
              <h2 className="text-2xl md:text-3xl font-bold">Want access to all playbooks?</h2>
              <p className="text-base text-muted-foreground max-w-2xl mx-auto">
                Join our private community and get instant access to every playbook, 
                plus new case studies added weekly from real founders.
              </p>
              <Link to="/apply">
                <Button size="lg" className="bg-primary hover:bg-primary/90 h-12 px-8">
                  Apply to Join the Community
                </Button>
              </Link>
            </CardContent>
          </Card>
        </div>
      </section>
    </div>
  );
};

export default Playbooks;
